package im.xgs.net.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("recent_contacter", "id", RecentContacter.class);
		arp.addMapping("sys_file", "id", SysFile.class);
		arp.addMapping("sys_friend_message", "id", SysFriendMessage.class);
		arp.addMapping("sys_group", "id", SysGroup.class);
		arp.addMapping("sys_group_files", "id", SysGroupFiles.class);
		arp.addMapping("sys_group_members", "id", SysGroupMembers.class);
		arp.addMapping("sys_group_message", "id", SysGroupMessage.class);
		arp.addMapping("sys_group_notice", "id", SysGroupNotice.class);
		arp.addMapping("sys_message", "id", SysMessage.class);
		arp.addMapping("sys_offline_message", "id", SysOfflineMessage.class);
		arp.addMapping("sys_org_user", "id", SysOrgUser.class);
		arp.addMapping("sys_org_user_message", "id", SysOrgUserMessage.class);
		arp.addMapping("sys_user", "user_id", SysUser.class);
		arp.addMapping("sys_user_friend", "id", SysUserFriend.class);
	}
}

