package im.xgs.net.model;

import im.xgs.net.model.base.BaseRecentContacter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecentContacter extends BaseRecentContacter<RecentContacter> {
	public static final RecentContacter dao = new RecentContacter();
}
