package im.xgs.net.model;

import im.xgs.net.model.base.BaseSysFriendMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysFriendMessage extends BaseSysFriendMessage<SysFriendMessage> {
	public static final SysFriendMessage dao = new SysFriendMessage();
}
