package im.xgs.net.model;

import im.xgs.net.model.base.BaseSysFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysFile extends BaseSysFile<SysFile> {
	public static final SysFile dao = new SysFile();
}
