package im.xgs.net.model;

import im.xgs.net.model.base.BaseSysGroupMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysGroupMessage extends BaseSysGroupMessage<SysGroupMessage> {
	public static final SysGroupMessage dao = new SysGroupMessage();
}
