package im.xgs.net.model;

import im.xgs.net.model.base.BaseSysGroupNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysGroupNotice extends BaseSysGroupNotice<SysGroupNotice> {
	public static final SysGroupNotice dao = new SysGroupNotice();
}
