package im.xgs.net.model;

import im.xgs.net.model.base.BaseSysGroupMembers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysGroupMembers extends BaseSysGroupMembers<SysGroupMembers> {
	public static final SysGroupMembers dao = new SysGroupMembers();
}
