package im.xgs.net.model;

import im.xgs.net.model.base.BaseSysGroupFiles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysGroupFiles extends BaseSysGroupFiles<SysGroupFiles> {
	public static final SysGroupFiles dao = new SysGroupFiles();
}
