package im.xgs.net.model;

import im.xgs.net.model.base.BaseSysGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysGroup extends BaseSysGroup<SysGroup> {
	public static final SysGroup dao = new SysGroup();
}
