package im.xgs.net.model;

import im.xgs.net.model.base.BaseSysMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMessage extends BaseSysMessage<SysMessage> {
	public static final SysMessage dao = new SysMessage();
}
