package im.xgs.net.model;

import im.xgs.net.model.base.BaseSysOfflineMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOfflineMessage extends BaseSysOfflineMessage<SysOfflineMessage> {
	public static final SysOfflineMessage dao = new SysOfflineMessage();
}
