package im.xgs.net.model;

import im.xgs.net.model.base.BaseSysOrgUserMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOrgUserMessage extends BaseSysOrgUserMessage<SysOrgUserMessage> {
	public static final SysOrgUserMessage dao = new SysOrgUserMessage();
}
