package im.xgs.net.model;

import im.xgs.net.model.base.BaseSysOrgUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOrgUser extends BaseSysOrgUser<SysOrgUser> {
	public static final SysOrgUser dao = new SysOrgUser();
}
