package im.xgs.net.model;

import im.xgs.net.model.base.BaseSysUserFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserFriend extends BaseSysUserFriend<SysUserFriend> {
	public static final SysUserFriend dao = new SysUserFriend();
}
