package im.xgs.net.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysMessage<M extends BaseSysMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setToUser(java.lang.String toUser) {
		set("to_user", toUser);
	}

	public java.lang.String getToUser() {
		return get("to_user");
	}

	public void setMessage(java.lang.String message) {
		set("message", message);
	}

	public java.lang.String getMessage() {
		return get("message");
	}

	public void setSendTime(java.lang.String sendTime) {
		set("send_time", sendTime);
	}

	public java.lang.String getSendTime() {
		return get("send_time");
	}

	public void setSearchYm(java.lang.String searchYm) {
		set("search_ym", searchYm);
	}

	public java.lang.String getSearchYm() {
		return get("search_ym");
	}

}
