package im.xgs.net.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysGroupMessage<M extends BaseSysGroupMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setToGroup(java.lang.String toGroup) {
		set("to_group", toGroup);
	}

	public java.lang.String getToGroup() {
		return get("to_group");
	}

	public void setFromUser(java.lang.String fromUser) {
		set("from_user", fromUser);
	}

	public java.lang.String getFromUser() {
		return get("from_user");
	}

	public void setMessage(java.lang.String message) {
		set("message", message);
	}

	public java.lang.String getMessage() {
		return get("message");
	}

	public void setSendTime(java.lang.String sendTime) {
		set("send_time", sendTime);
	}

	public java.lang.String getSendTime() {
		return get("send_time");
	}

	public void setSearchYm(java.lang.String searchYm) {
		set("search_ym", searchYm);
	}

	public java.lang.String getSearchYm() {
		return get("search_ym");
	}

}
