package im.xgs.net.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysOrgUser<M extends BaseSysOrgUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setLoginAccount(java.lang.String loginAccount) {
		set("login_account", loginAccount);
	}

	public java.lang.String getLoginAccount() {
		return get("login_account");
	}

	public void setLoginPwd(java.lang.String loginPwd) {
		set("login_pwd", loginPwd);
	}

	public java.lang.String getLoginPwd() {
		return get("login_pwd");
	}

	public void setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
	}

	public java.lang.String getParentId() {
		return get("parent_id");
	}

	public void setLeaf(java.lang.Boolean leaf) {
		set("leaf", leaf);
	}

	public java.lang.Boolean getLeaf() {
		return get("leaf");
	}

}
